from __future__ import annotations

import io
import logging
import os
import tempfile
from datetime import datetime

from jinja2 import Environment, BaseLoader
from weasyprint import HTML, CSS

from app.models.evidence_pack import EvidencePackContent

log = logging.getLogger(__name__)

# ─── CSS Stylesheet ───────────────────────────────────────────────────────────

_PACK_CSS = """
@page {
    size: letter;
    margin: 1in 1in 0.85in 1in;
    @bottom-center {
        content: "ATTORNEY-CLIENT PRIVILEGED — WORK PRODUCT  |  Case " string(case-id) "  |  Page " counter(page) " of " counter(pages) "  |  Generated by ExitForge";
        font-size: 8pt;
        color: #666;
        font-family: 'Georgia', serif;
    }
}

body {
    font-family: 'Georgia', serif;
    font-size: 11pt;
    line-height: 1.5;
    color: #1a1a1a;
}

h1 { font-size: 18pt; color: #1a1a2e; margin-top: 1.5em; border-bottom: 2pt solid #1a1a2e; padding-bottom: 4pt; }
h2 { font-size: 14pt; color: #1a1a2e; margin-top: 1.2em; }
h3 { font-size: 12pt; color: #333; margin-top: 1em; }

.cover-page {
    text-align: center;
    page-break-after: always;
    padding-top: 2in;
}
.cover-title { font-size: 24pt; font-weight: bold; color: #1a1a2e; }
.cover-subtitle { font-size: 14pt; color: #666; margin-top: 0.5em; }
.cover-case-info { margin-top: 2em; font-size: 12pt; }
.cover-case-info td { padding: 4pt 8pt; }
.cover-label { font-weight: bold; text-align: right; }

.strength-strong { color: #1a7a1a; font-weight: bold; }
.strength-moderate { color: #b87700; font-weight: bold; }
.strength-borderline { color: #cc2200; font-weight: bold; }

.toc { page-break-after: always; }
.toc h2 { margin-bottom: 1em; }
.toc-entry { display: flex; justify-content: space-between; padding: 2pt 0; border-bottom: 1pt dotted #ccc; }

.section { page-break-before: always; }
.section-header { background-color: #1a1a2e; color: white; padding: 8pt 12pt; margin-bottom: 1em; }
.section-header h2 { color: white; border: none; margin: 0; }

.warning-box { background: #fff3cd; border: 1pt solid #ffc107; padding: 8pt; margin: 1em 0; }
.critical-box { background: #ffeaea; border: 1pt solid #cc2200; padding: 8pt; margin: 1em 0; }
.info-box { background: #e8f4fd; border: 1pt solid #0066cc; padding: 8pt; margin: 1em 0; }

table { width: 100%; border-collapse: collapse; margin: 1em 0; font-size: 10pt; }
th { background: #1a1a2e; color: white; padding: 6pt 8pt; text-align: left; }
td { padding: 5pt 8pt; border-bottom: 0.5pt solid #ddd; vertical-align: top; }
tr:nth-child(even) td { background: #f8f8f8; }

.leverage-high { color: #1a7a1a; font-weight: bold; }
.leverage-medium { color: #b87700; font-weight: bold; }
.leverage-low { color: #666; }

.demand-letter {
    font-family: 'Courier New', monospace;
    font-size: 10pt;
    line-height: 1.6;
    border: 1pt solid #ccc;
    padding: 16pt;
    background: #fafafa;
    white-space: pre-wrap;
}

.declaration { font-size: 10pt; line-height: 1.7; }
.statement-number { font-weight: bold; color: #1a1a2e; }
.attestation { margin-top: 2em; border-top: 1pt solid #ccc; padding-top: 1em; font-style: italic; }
.signature-line { margin-top: 3em; border-top: 1pt solid #333; width: 60%; }

.footer-note { font-size: 8pt; color: #666; font-style: italic; margin-top: 2em; border-top: 0.5pt solid #ccc; padding-top: 0.5em; }
"""


# ─── Jinja2 Template ──────────────────────────────────────────────────────────

_PACK_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Attorney Evidence Pack — {{ pack.case_id }}</title>
<style>{{ css }}</style>
</head>
<body>

<!-- COVER PAGE -->
<div class="cover-page">
  <div class="cover-title">ATTORNEY EVIDENCE PACK</div>
  <div class="cover-subtitle">CONFIDENTIAL — ATTORNEY-CLIENT PRIVILEGED — WORK PRODUCT</div>
  <table class="cover-case-info" style="margin: 2em auto; width: 70%;">
    <tr><td class="cover-label">Client:</td><td>{{ s1.client_full_name }}</td></tr>
    <tr><td class="cover-label">Case ID:</td><td style="string-set: case-id '{{ pack.case_id }}'">{{ pack.case_id }}</td></tr>
    <tr><td class="cover-label">Resort:</td><td>{{ s1.resort_name }}</td></tr>
    <tr><td class="cover-label">Developer:</td><td>{{ s1.resort_developer }}</td></tr>
    <tr><td class="cover-label">Case Strength:</td>
      <td class="strength-{{ s1.case_strength_rating | lower }}">{{ s1.case_strength_rating }}</td></tr>
    <tr><td class="cover-label">Generated:</td><td>{{ pack.generated_at[:10] }}</td></tr>
    {% if attorney_name %}<tr><td class="cover-label">Prepared for:</td><td>{{ attorney_name }}</td></tr>{% endif %}
  </table>
  <div style="margin-top: 3em; font-size: 10pt; color: #666; max-width: 5in; margin-left: auto; margin-right: auto;">
    This pack was prepared by ExitForge AI Legal Operations. All statute citations should be independently 
    verified before reliance in any legal proceeding. This document is protected by attorney-client privilege 
    and attorney work product doctrine.
  </div>
</div>

<!-- TABLE OF CONTENTS -->
<div class="toc">
  <h2>Table of Contents</h2>
  <div class="toc-entry"><span>1. Executive Summary</span></div>
  <div class="toc-entry"><span>2. Client Declaration</span></div>
  <div class="toc-entry"><span>3. Contract Analysis</span></div>
  <div class="toc-entry"><span>4. Misrepresentation Matrix</span></div>
  <div class="toc-entry"><span>5. Applicable Law Brief</span></div>
  <div class="toc-entry"><span>6. Financial Impact Analysis</span></div>
  <div class="toc-entry"><span>7. Resort Profile and Intelligence</span></div>
  <div class="toc-entry"><span>8. Prior Negotiation History</span></div>
  <div class="toc-entry"><span>9. Demand Letter Draft</span></div>
  {% if pack.section10_cfpb_complaint_draft %}<div class="toc-entry"><span>10. CFPB Complaint Draft</span></div>{% endif %}
  <div class="toc-entry"><span>11. Supporting Documents Index</span></div>
</div>

<!-- SECTION 1: EXECUTIVE SUMMARY -->
<div class="section">
  <div class="section-header"><h2>Section 1 — Executive Summary</h2></div>
  <table>
    <tr><td><strong>Case Strength:</strong></td><td class="strength-{{ s1.case_strength_rating | lower }}">{{ s1.case_strength_rating }}</td>
        <td><strong>Recommended Action:</strong></td><td>{{ s1.recommended_immediate_action }}</td></tr>
    <tr><td><strong>Purchase Price:</strong></td><td>${{ "{:,.2f}".format(s1.purchase_price) }}</td>
        <td><strong>Total Exposure:</strong></td><td>${{ "{:,.2f}".format(s1.total_financial_exposure) }}</td></tr>
    <tr><td><strong>Maintenance Fee:</strong></td><td>${{ "{:,.2f}".format(s1.current_maintenance_fee_annual) }}/yr</td>
        <td><strong>Outstanding Mortgage:</strong></td><td>${{ "{:,.2f}".format(s1.outstanding_mortgage) }}</td></tr>
  </table>
  <h3>Primary Legal Grounds</h3>
  <ol>{% for ground in s1.primary_legal_grounds %}<li>{{ ground }}</li>{% endfor %}</ol>
  {% if s1.key_deadlines %}
  <h3>Key Deadlines</h3>
  <table>
    <tr><th>Deadline</th><th>Date</th><th>Significance</th></tr>
    {% for d in s1.key_deadlines %}
    <tr>
      <td>{% if d.is_missed %}<strong style="color:#cc2200">⚠ MISSED: </strong>{% endif %}{{ d.description }}</td>
      <td>{{ d.date or "N/A" }}</td>
      <td>{{ d.legal_significance }}</td>
    </tr>
    {% endfor %}
  </table>
  {% endif %}
  <h3>Case Narrative</h3>
  <p>{{ s1.one_page_narrative | replace('\n', '<br>') }}</p>
</div>

<!-- SECTION 2: CLIENT DECLARATION -->
<div class="section">
  <div class="section-header"><h2>Section 2 — Client Declaration</h2></div>
  <div class="declaration">
  <p><strong>DECLARATION OF {{ s2.client_name | upper }}</strong></p>
  <p>I, {{ s2.client_name }}, declare as follows:</p>
  {% for stmt in s2.misrepresentation_statements %}
  <p><span class="statement-number">{{ stmt.statement_number }}.</span>
    <strong>{{ stmt.category }}</strong>: {{ stmt.what_was_told_to_client }}
    {% if not stmt.is_verified_by_contract_text %}
    <em>(Note: This statement rests on client testimony and has not been independently corroborated by contract text.)</em>
    {% endif %}<br>
    <em>Contract states ({{ stmt.contract_page_reference }}): {{ stmt.what_contract_actually_says }}</em><br>
    <em>Applicable statute: {{ stmt.applicable_statute }}</em>
  </p>
  {% endfor %}
  {% if s2.is_rescission_violation is defined and s2.is_rescission_violation %}
  <div class="critical-box">
    <strong>RESCISSION VIOLATION:</strong> Client was entitled to {{ s2.actual_rescission_period_by_law }} days 
    to cancel. {% if s2.rescission_period_days_stated %}Contract stated {{ s2.rescission_period_days_stated }} days.{% endif %}
  </div>
  {% endif %}
  <div class="attestation">
    {{ s2.declaration_text }}
    <div class="signature-line"></div>
    <p>{{ s2.client_name }}<br>Date: _______________________</p>
  </div>
  </div>
</div>

<!-- SECTION 3: CONTRACT ANALYSIS -->
<div class="section">
  <div class="section-header"><h2>Section 3 — Contract Analysis</h2></div>
  <p><strong>Leverage Score:</strong> {{ "%.0f"|format(s3.leverage_score * 100) }}% &nbsp;|&nbsp;
     <strong>OCR Confidence:</strong> {{ "%.0f"|format(s3.ocr_confidence_score * 100) }}%</p>
  <p>{{ s3.leverage_narrative }}</p>
  <p>{{ s3.illegal_terms_summary }}</p>
  {% if s3.critical_flags %}
  <h3>Critical Flags ({{ s3.critical_flags | length }})</h3>
  <table>
    <tr><th>Clause</th><th>Verbatim Text</th><th>Why Problematic</th><th>Statute</th></tr>
    {% for c in s3.critical_flags %}
    <tr><td>{{ c.section_reference }}</td><td><em>{{ c.verbatim_text[:200] }}</em></td>
        <td>{{ c.why_problematic }}</td><td>{{ c.applicable_statute }}</td></tr>
    {% endfor %}
  </table>
  {% endif %}
  {% if s3.major_flags %}
  <h3>Major Flags ({{ s3.major_flags | length }})</h3>
  <table>
    <tr><th>Clause</th><th>Verbatim Text</th><th>Why Problematic</th></tr>
    {% for c in s3.major_flags %}
    <tr><td>{{ c.section_reference }}</td><td><em>{{ c.verbatim_text[:200] }}</em></td>
        <td>{{ c.why_problematic }}</td></tr>
    {% endfor %}
  </table>
  {% endif %}
</div>

<!-- SECTION 4: MISREPRESENTATION MATRIX -->
<div class="section">
  <div class="section-header"><h2>Section 4 — Misrepresentation Matrix</h2></div>
  <p><strong>Total misrepresentations found:</strong> {{ s4.total_misrepresentations_found }} &nbsp;|&nbsp;
     <strong>Overall score:</strong> {{ "%.0f"|format(s4.overall_misrepresentation_score * 100) }}%</p>
  <div class="info-box"><strong>Prosecutorial Narrative:</strong><br>{{ s4.prosecutorial_narrative }}</div>
  <table>
    <tr><th>#</th><th>Category</th><th>Client Allegation</th><th>Contract Contradiction</th><th>Citation</th><th>Leverage</th></tr>
    {% for e in s4.entries %}
    <tr>
      <td>{{ e.id }}</td>
      <td>{{ e.category }}</td>
      <td>{{ e.client_allegation }}</td>
      <td>{{ e.contract_contradiction }}</td>
      <td>{{ e.contract_page_citation }}</td>
      <td class="leverage-{{ e.settlement_leverage | lower }}">{{ e.settlement_leverage }}</td>
    </tr>
    {% endfor %}
  </table>
</div>

<!-- SECTION 5: APPLICABLE LAW -->
<div class="section">
  <div class="section-header"><h2>Section 5 — Applicable Law Brief</h2></div>
  <p><strong>Jurisdiction:</strong> {{ s5.jurisdiction }}</p>
  {% set sol = s5.statute_of_limitations_analysis %}
  {% if sol.urgency_note %}
  <div class="critical-box">{{ sol.urgency_note }}</div>
  {% endif %}
  <h3>Primary State Statutes</h3>
  {% for s in s5.primary_statutes %}
  <div style="margin-bottom: 1em;">
    <strong>{{ s.name }}</strong> — {{ s.citation }}<br>
    {% if s.is_violated %}<span style="color:#cc2200">✗ VIOLATED:</span>{% else %}<span style="color:#1a7a1a">✓</span>{% endif %}
    {{ s.how_it_applies }}<br>
    <em>Remedies: {{ s.remedies_available | join("; ") }}</em>
  </div>
  {% endfor %}
  <h3>Federal Law</h3>
  {% for f in s5.federal_law %}
  <div style="margin-bottom: 0.5em;">
    <strong>{{ f.name }}</strong> — {{ f.citation }}: {{ f.how_it_applies }}
  </div>
  {% endfor %}
  <h3>Statute of Limitations</h3>
  <table>
    <tr><td><strong>Purchase Date:</strong></td><td>{{ sol.purchase_date }}</td>
        <td><strong>State SOL:</strong></td><td>{{ sol.state_sol }} years</td></tr>
    <tr><td><strong>SOL Expiry:</strong></td><td>{{ sol.sol_expiry_date }}</td>
        <td><strong>Within SOL:</strong></td>
        <td>{% if sol.is_within_sol %}<span style="color:#1a7a1a">YES</span>{% else %}<span style="color:#cc2200">NO — ANALYZE TOLLING</span>{% endif %}</td></tr>
  </table>
  {% if sol.tollable_event_exists %}
  <div class="warning-box"><strong>Tolling argument:</strong> {{ sol.tollable_event_description }}</div>
  {% endif %}
  <p>{{ s5.jurisdictional_notes }}</p>
</div>

<!-- SECTION 6: FINANCIAL IMPACT -->
<div class="section">
  <div class="section-header"><h2>Section 6 — Financial Impact Analysis</h2></div>
  <table>
    <tr><th colspan="2">Financial Summary</th></tr>
    <tr><td>Purchase Price</td><td>${{ "{:,.2f}".format(s6.purchase_price) }}</td></tr>
    <tr><td>Current Mortgage Balance</td><td>${{ "{:,.2f}".format(s6.current_mortgage_balance) }}</td></tr>
    <tr><td>Maintenance Fee (Current Year)</td><td>${{ "{:,.2f}".format(s6.maintenance_fee_current_year) }}/yr</td></tr>
    <tr><td>Projected Maintenance Fee (5yr)</td><td>${{ "{:,.2f}".format(s6.maintenance_fee_projected_5_years) }}/yr</td></tr>
    <tr><td>Projected Maintenance Fee (10yr)</td><td>${{ "{:,.2f}".format(s6.maintenance_fee_projected_10_years) }}/yr</td></tr>
    <tr><td>Total Paid to Date</td><td>${{ "{:,.2f}".format(s6.total_paid_to_date) }}</td></tr>
    <tr><td><strong>Total Exposure If No Exit</strong></td><td><strong>${{ "{:,.2f}".format(s6.total_exposure_if_no_exit) }}</strong></td></tr>
    <tr><td><strong>Estimated Damages Claim</strong></td><td><strong>${{ "{:,.2f}".format(s6.estimated_damages_claim) }}</strong></td></tr>
  </table>
  <h3>Damages Breakdown</h3>
  <table>
    <tr><th>Description</th><th>Amount</th><th>Legal Basis</th><th>Type</th></tr>
    {% for d in s6.damages_breakdown %}
    <tr><td>{{ d.description }}</td><td>${{ "{:,.2f}".format(d.amount) }}</td>
        <td>{{ d.legal_basis }}</td>
        <td>{% if d.is_special_damages %}Special{% else %}General{% endif %}</td></tr>
    {% endfor %}
  </table>
  {% if s6.financial_hardship_narrative %}
  <p>{{ s6.financial_hardship_narrative }}</p>
  {% endif %}
</div>

<!-- SECTION 7: RESORT PROFILE -->
<div class="section">
  <div class="section-header"><h2>Section 7 — Resort Profile and Intelligence</h2></div>
  <table>
    <tr><td><strong>Developer:</strong></td><td>{{ s7.developer_name }}</td>
        <td><strong>State:</strong></td><td>{{ s7.resort_state }}</td></tr>
    <tr><td><strong>Resistance Score:</strong></td><td>{{ "%.0f"|format(s7.resistance_score * 100) }}%</td>
        <td><strong>Deed-Back Available:</strong></td>
        <td>{% if s7.historical_deed_back_acceptance %}YES{% else %}NO{% endif %}</td></tr>
    <tr><td><strong>Avg Days to Resolution:</strong></td><td>{{ s7.avg_days_to_resolution }}</td>
        <td><strong>Historical Success Rate:</strong></td><td>{{ "%.0f"|format(s7.historical_success_rate * 100) }}%</td></tr>
  </table>
  {% if s7.known_vulnerabilities %}
  <h3>Known Legal Vulnerabilities</h3>
  <ul>{% for v in s7.known_vulnerabilities %}<li>{{ v }}</li>{% endfor %}</ul>
  {% endif %}
  <h3>Negotiation Intelligence</h3>
  <p>{{ s7.negotiation_intelligence }}</p>
  <h3>Recommended Approach</h3>
  <p>{{ s7.recommended_approach }}</p>
  {% if s7.prior_regulatory_actions %}
  <h3>Prior Regulatory Actions</h3>
  <table>
    <tr><th>Agency</th><th>Year</th><th>Description</th><th>Outcome</th></tr>
    {% for a in s7.prior_regulatory_actions %}
    <tr><td>{{ a.agency }}</td><td>{{ a.year }}</td><td>{{ a.description }}</td><td>{{ a.outcome }}</td></tr>
    {% endfor %}
  </table>
  {% endif %}
</div>

<!-- SECTION 8: NEGOTIATION HISTORY -->
<div class="section">
  <div class="section-header"><h2>Section 8 — Prior Negotiation History</h2></div>
  <p><strong>Total Rounds:</strong> {{ s8.total_rounds }} &nbsp;|&nbsp; <strong>Current Status:</strong> {{ s8.current_status }}</p>
  {% if s8.rounds %}
  <table>
    <tr><th>Round</th><th>Track</th><th>Letter Sent</th><th>Response</th><th>Response Type</th></tr>
    {% for r in s8.rounds %}
    <tr><td>{{ r.round_number }}</td><td>{{ r.track }}</td>
        <td>{{ r.letter_sent_date or "Pending" }}</td>
        <td>{{ r.response_date or "No response" }}</td>
        <td>{{ r.response_type or "—" }}</td></tr>
    {% endfor %}
  </table>
  {% endif %}
  <h3>Resort Response Pattern</h3>
  <p>{{ s8.resort_response_pattern }}</p>
  <h3>Recommended Next Step</h3>
  <div class="info-box">{{ s8.recommended_next_step }}</div>
</div>

<!-- SECTION 9: DEMAND LETTER -->
<div class="section">
  <div class="section-header"><h2>Section 9 — Demand Letter Draft</h2></div>
  <div class="warning-box">
    <strong>Attorney Instructions:</strong> {{ s9.instructions_for_attorney }}<br>
    {% if s9.warnings_for_attorney %}
    <strong>Warnings:</strong>
    <ul>{% for w in s9.warnings_for_attorney %}<li>{{ w }}</li>{% endfor %}</ul>
    {% endif %}
  </div>
  <div class="demand-letter">{{ s9.letter_draft }}</div>
  <div class="footer-note">
    Legal grounds: {{ s9.legal_grounds_used | join("; ") }}<br>
    Statutes cited: {{ s9.statutes_cited | join("; ") }}<br>
    Tone rationale: {{ s9.tone_rationale }}
  </div>
</div>

<!-- SECTION 10: CFPB COMPLAINT (optional) -->
{% if s10 %}
<div class="section">
  <div class="section-header"><h2>Section 10 — CFPB Complaint Draft</h2></div>
  <div class="info-box">
    <strong>Product:</strong> {{ s10.product_type }}<br>
    <strong>Issue:</strong> {{ s10.issue_category }} — {{ s10.sub_issue }}<br>
    <strong>Company:</strong> {{ s10.company_cfpb_name }}, {{ s10.company_address }}
  </div>
  <h3>Complaint Narrative</h3>
  <div style="border: 1pt solid #ccc; padding: 12pt; background: #fafafa;">{{ s10.complaint_narrative }}</div>
  <p><strong>Desired Resolution:</strong> {{ s10.desired_resolution }}</p>
  <h3>Filing Instructions</h3>
  <p>{{ s10.filing_instructions }}</p>
</div>
{% endif %}

<!-- SECTION 11: SUPPORTING DOCUMENTS -->
<div class="section">
  <div class="section-header"><h2>Section 11 — Supporting Documents Index</h2></div>
  {% if s11.documents %}
  <table>
    <tr><th>Document Type</th><th>Description</th><th>Uploaded</th><th>Relevance</th><th>Access</th></tr>
    {% for d in s11.documents %}
    <tr>
      <td>{{ d.document_type }}</td>
      <td>{{ d.description }}</td>
      <td>{{ d.uploaded_at[:10] if d.uploaded_at else "N/A" }}</td>
      <td>{{ d.relevance_to_case }}</td>
      <td><a href="{{ d.presigned_url }}">Download (7-day link)</a></td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
  <p>No documents uploaded to the case file.</p>
  {% endif %}
  {% if s11.missing_document_recommendations %}
  <h3>Missing Document Recommendations</h3>
  <ul>{% for m in s11.missing_document_recommendations %}<li>{{ m }}</li>{% endfor %}</ul>
  {% endif %}
</div>

</body>
</html>"""


# ─── Generator ────────────────────────────────────────────────────────────────

def generate_pdf(content: EvidencePackContent, attorney_name: str | None = None) -> bytes:
    """
    Render a WeasyPrint PDF from an EvidencePackContent object.
    Returns raw PDF bytes. Store in S3 after calling this function.
    """
    env = Environment(loader=BaseLoader())
    template = env.from_string(_PACK_TEMPLATE)

    html_str = template.render(
        pack=content,
        css=_PACK_CSS,
        attorney_name=attorney_name,
        s1=content.section1_executive_summary,
        s2=content.section2_client_declaration,
        s3=content.section3_contract_analysis,
        s4=content.section4_misrepresentation_matrix,
        s5=content.section5_applicable_law,
        s6=content.section6_financial_impact,
        s7=content.section7_resort_profile,
        s8=content.section8_negotiation_history,
        s9=content.section9_demand_letter_draft,
        s10=content.section10_cfpb_complaint_draft,
        s11=content.section11_supporting_documents,
    )

    log.info("pdf_render_started", pack_id=content.pack_id)

    with tempfile.NamedTemporaryFile(suffix=".html", delete=False, mode="w", encoding="utf-8") as f:
        f.write(html_str)
        tmp_path = f.name

    try:
        pdf_bytes = HTML(filename=tmp_path).write_pdf(
            presentational_hints=True,
        )
    finally:
        os.unlink(tmp_path)

    log.info("pdf_render_complete", pack_id=content.pack_id, size_bytes=len(pdf_bytes))
    return pdf_bytes
