from __future__ import annotations

"""
Per-state statute database for timeshare cases.
Covers the 12 primary timeshare states by volume of sales and disputes.
These are factual legal citations — verified by reference to state codes.
"""

# ─── State Statute Database ───────────────────────────────────────────────────

_STATE_STATUTES: dict[str, dict] = {
    "FL": {
        "state": "Florida",
        "rescission_days": 10,
        "sol_years": 5,
        "primary_statute_name": "Florida Vacation Plan and Timesharing Act",
        "primary_statute_citation": "Fla. Stat. §§ 721.01–721.26",
        "key_provision": "§ 721.10 — Purchaser has 10-day right to cancel; § 721.08 — Required disclosure requirements",
        "consumer_protection_name": "Florida Deceptive and Unfair Trade Practices Act (FDUTPA)",
        "consumer_protection_citation": "Fla. Stat. §§ 501.201–501.213",
        "misrepresentation_voids_contract": True,
        "attorney_fees_available": True,
        "punitive_damages_available": True,
        "punitive_damages_cap": "3x actual damages",
        "state_ag_complaint_url": "https://myfloridalegal.com/",
        "regulatory_body": "Florida Department of Business and Professional Regulation (DBPR)",
        "regulatory_url": "https://www.myfloridalicense.com/",
        "notes": "Florida has among the strongest timeshare consumer protections. DBPR can revoke developer licenses.",
    },
    "NV": {
        "state": "Nevada",
        "rescission_days": 5,
        "sol_years": 6,
        "primary_statute_name": "Nevada Timeshare Act",
        "primary_statute_citation": "Nev. Rev. Stat. §§ 119A.010–119A.650",
        "key_provision": "§ 119A.355 — Cancellation rights; § 119A.290 — Disclosure requirements",
        "consumer_protection_name": "Nevada Deceptive Trade Practices Act",
        "consumer_protection_citation": "Nev. Rev. Stat. §§ 598.0903–598.0999",
        "misrepresentation_voids_contract": True,
        "attorney_fees_available": True,
        "punitive_damages_available": True,
        "punitive_damages_cap": None,
        "state_ag_complaint_url": "https://ag.nv.gov/Complaints/File_Complaint/",
        "regulatory_body": "Nevada Real Estate Division",
        "regulatory_url": "https://red.nv.gov/",
        "notes": "Nevada's 5-day rescission period is shorter than most states. Concealment of rescission rights is a strong statutory violation.",
    },
    "AZ": {
        "state": "Arizona",
        "rescission_days": 7,
        "sol_years": 6,
        "primary_statute_name": "Arizona Timeshare Act",
        "primary_statute_citation": "Ariz. Rev. Stat. §§ 33-2201 to 33-2218",
        "key_provision": "§ 33-2204 — Rescission period; § 33-2205 — Prohibited practices",
        "consumer_protection_name": "Arizona Consumer Fraud Act",
        "consumer_protection_citation": "Ariz. Rev. Stat. §§ 44-1521 to 44-1534",
        "misrepresentation_voids_contract": True,
        "attorney_fees_available": True,
        "punitive_damages_available": True,
        "punitive_damages_cap": None,
        "state_ag_complaint_url": "https://www.azag.gov/complaints/consumer",
        "regulatory_body": "Arizona Department of Real Estate",
        "regulatory_url": "https://azre.gov/",
        "notes": "Arizona AG has historically been active in pursuing timeshare fraud cases.",
    },
    "SC": {
        "state": "South Carolina",
        "rescission_days": 5,
        "sol_years": 3,
        "primary_statute_name": "South Carolina Vacation Time Sharing Plans Act",
        "primary_statute_citation": "S.C. Code Ann. §§ 27-32-10 to 27-32-270",
        "key_provision": "§ 27-32-80 — Cancellation period; § 27-32-170 — Developer obligations",
        "consumer_protection_name": "South Carolina Unfair Trade Practices Act",
        "consumer_protection_citation": "S.C. Code Ann. §§ 39-5-10 to 39-5-160",
        "misrepresentation_voids_contract": True,
        "attorney_fees_available": True,
        "punitive_damages_available": False,
        "punitive_damages_cap": None,
        "state_ag_complaint_url": "https://www.scag.gov/for-citizens/file-a-consumer-complaint/",
        "regulatory_body": "South Carolina Real Estate Commission",
        "regulatory_url": "https://llr.sc.gov/rec/",
        "notes": "South Carolina has shorter SOL; analyze tolling carefully.",
    },
    "TN": {
        "state": "Tennessee",
        "rescission_days": 10,
        "sol_years": 6,
        "primary_statute_name": "Tennessee Time-Share Act",
        "primary_statute_citation": "Tenn. Code Ann. §§ 66-32-101 to 66-32-124",
        "key_provision": "§ 66-32-108 — Cancellation right; § 66-32-106 — Disclosure requirements",
        "consumer_protection_name": "Tennessee Consumer Protection Act",
        "consumer_protection_citation": "Tenn. Code Ann. §§ 47-18-101 to 47-18-130",
        "misrepresentation_voids_contract": True,
        "attorney_fees_available": True,
        "punitive_damages_available": True,
        "punitive_damages_cap": None,
        "state_ag_complaint_url": "https://www.tn.gov/attorneygeneral/consumer-protection.html",
        "regulatory_body": "Tennessee Real Estate Commission",
        "regulatory_url": "https://www.tn.gov/commerce/regboards/trec.html",
        "notes": "Tennessee Attorney General has filed several timeshare enforcement actions.",
    },
    "MO": {
        "state": "Missouri",
        "rescission_days": 5,
        "sol_years": 5,
        "primary_statute_name": "Missouri Timeshare Act",
        "primary_statute_citation": "Mo. Rev. Stat. §§ 407.600–407.650",
        "key_provision": "§ 407.615 — Cancellation rights; § 407.610 — Required disclosures",
        "consumer_protection_name": "Missouri Merchandising Practices Act",
        "consumer_protection_citation": "Mo. Rev. Stat. § 407.010 et seq.",
        "misrepresentation_voids_contract": True,
        "attorney_fees_available": True,
        "punitive_damages_available": True,
        "punitive_damages_cap": None,
        "state_ag_complaint_url": "https://ago.mo.gov/consumer-protection/file-a-complaint",
        "regulatory_body": "Missouri Division of Finance",
        "regulatory_url": "https://finance.mo.gov/",
        "notes": "Missouri Merchandising Practices Act is broadly written and highly effective in timeshare cases.",
    },
    "GA": {
        "state": "Georgia",
        "rescission_days": 7,
        "sol_years": 6,
        "primary_statute_name": "Georgia Time-Share Act",
        "primary_statute_citation": "Ga. Code Ann. §§ 44-3-160 to 44-3-175",
        "key_provision": "§ 44-3-167 — Cancellation period; § 44-3-163 — Disclosures",
        "consumer_protection_name": "Georgia Fair Business Practices Act",
        "consumer_protection_citation": "Ga. Code Ann. §§ 10-1-390 to 10-1-408",
        "misrepresentation_voids_contract": True,
        "attorney_fees_available": True,
        "punitive_damages_available": True,
        "punitive_damages_cap": "$250,000 per defendant",
        "state_ag_complaint_url": "https://consumer.georgia.gov/contact-us",
        "regulatory_body": "Georgia Real Estate Commission",
        "regulatory_url": "https://grec.state.ga.us/",
        "notes": "Georgia punitive damages cap applies per defendant, not per claim.",
    },
    "HI": {
        "state": "Hawaii",
        "rescission_days": 7,
        "sol_years": 6,
        "primary_statute_name": "Hawaii Timesharing Plans Act",
        "primary_statute_citation": "Haw. Rev. Stat. §§ 514E-1 to 514E-21",
        "key_provision": "§ 514E-8 — Purchaser's right of cancellation; § 514E-5 — Disclosure requirements",
        "consumer_protection_name": "Hawaii Consumer Protection Act",
        "consumer_protection_citation": "Haw. Rev. Stat. §§ 480-1 to 480-24",
        "misrepresentation_voids_contract": True,
        "attorney_fees_available": True,
        "punitive_damages_available": True,
        "punitive_damages_cap": None,
        "state_ag_complaint_url": "https://cca.hawaii.gov/rico/complaint/",
        "regulatory_body": "Hawaii Real Estate Commission",
        "regulatory_url": "https://cca.hawaii.gov/reb/",
        "notes": "Hawaii has mandatory timeshare registration. Unregistered timeshares may be voidable.",
    },
    "VA": {
        "state": "Virginia",
        "rescission_days": 7,
        "sol_years": 5,
        "primary_statute_name": "Virginia Real Estate Time-Share Act",
        "primary_statute_citation": "Va. Code Ann. §§ 55.1-2200 to 55.1-2260",
        "key_provision": "§ 55.1-2217 — Cancellation right; § 55.1-2210 — Public offering statement",
        "consumer_protection_name": "Virginia Consumer Protection Act",
        "consumer_protection_citation": "Va. Code Ann. §§ 59.1-196 to 59.1-207",
        "misrepresentation_voids_contract": True,
        "attorney_fees_available": True,
        "punitive_damages_available": True,
        "punitive_damages_cap": "$350,000",
        "state_ag_complaint_url": "https://www.oag.state.va.us/consumer-protection/index.php/file-a-complaint",
        "regulatory_body": "Virginia Department of Professional and Occupational Regulation",
        "regulatory_url": "https://www.dpor.virginia.gov/",
        "notes": "Virginia AG has authority to seek restitution and civil penalties in timeshare fraud cases.",
    },
    "CO": {
        "state": "Colorado",
        "rescission_days": 5,
        "sol_years": 6,
        "primary_statute_name": "Colorado Timeshare Act",
        "primary_statute_citation": "Colo. Rev. Stat. §§ 12-61-401 to 12-61-420",
        "key_provision": "§ 12-61-407 — Right of cancellation; § 12-61-404 — Required disclosures",
        "consumer_protection_name": "Colorado Consumer Protection Act",
        "consumer_protection_citation": "Colo. Rev. Stat. §§ 6-1-101 to 6-1-1001",
        "misrepresentation_voids_contract": True,
        "attorney_fees_available": True,
        "punitive_damages_available": True,
        "punitive_damages_cap": None,
        "state_ag_complaint_url": "https://coag.gov/office-sections/consumer-protection/consumer-complaint-referral/",
        "regulatory_body": "Colorado Division of Real Estate",
        "regulatory_url": "https://dre.colorado.gov/",
        "notes": "Colorado Consumer Protection Act treble damages provision is powerful in timeshare fraud cases.",
    },
    "CA": {
        "state": "California",
        "rescission_days": 7,
        "sol_years": 4,
        "primary_statute_name": "California Vacation Ownership and Time-share Act of 2004",
        "primary_statute_citation": "Cal. Bus. & Prof. Code §§ 11210–11290",
        "key_provision": "§ 11238 — Right of rescission; § 11235 — Public report requirement",
        "consumer_protection_name": "California Consumer Legal Remedies Act (CLRA) and UCL",
        "consumer_protection_citation": "Cal. Civ. Code §§ 1750–1784; Cal. Bus. & Prof. Code §§ 17200–17210",
        "misrepresentation_voids_contract": True,
        "attorney_fees_available": True,
        "punitive_damages_available": True,
        "punitive_damages_cap": None,
        "state_ag_complaint_url": "https://oag.ca.gov/consumers/general/complaint",
        "regulatory_body": "California Department of Real Estate",
        "regulatory_url": "https://www.dre.ca.gov/",
        "notes": "California has particularly strong consumer protection statutes. Class actions are common.",
    },
    "TX": {
        "state": "Texas",
        "rescission_days": 6,
        "sol_years": 4,
        "primary_statute_name": "Texas Timeshare Act",
        "primary_statute_citation": "Tex. Prop. Code Ann. §§ 221.001–221.101",
        "key_provision": "§ 221.041 — Purchaser's right of cancellation; § 221.033 — Disclosure requirements",
        "consumer_protection_name": "Texas Deceptive Trade Practices Act (DTPA)",
        "consumer_protection_citation": "Tex. Bus. & Com. Code §§ 17.41–17.63",
        "misrepresentation_voids_contract": True,
        "attorney_fees_available": True,
        "punitive_damages_available": True,
        "punitive_damages_cap": None,
        "state_ag_complaint_url": "https://www.texasattorneygeneral.gov/consumer-protection/file-consumer-complaint",
        "regulatory_body": "Texas Real Estate Commission",
        "regulatory_url": "https://www.trec.texas.gov/",
        "notes": "Texas DTPA allows treble damages and attorney fees for knowing violations.",
    },
}

_DEFAULT_STATUTE = {
    "state": "Unknown",
    "rescission_days": 7,
    "sol_years": 5,
    "primary_statute_name": "State Timeshare Act",
    "primary_statute_citation": "State timeshare statutes (jurisdiction-specific — verify with local counsel)",
    "key_provision": "Rescission and disclosure requirements",
    "consumer_protection_name": "State Consumer Protection Act",
    "consumer_protection_citation": "State consumer protection statutes",
    "misrepresentation_voids_contract": True,
    "attorney_fees_available": False,
    "punitive_damages_available": False,
    "punitive_damages_cap": None,
    "state_ag_complaint_url": "https://www.naag.org/find-my-ag/",
    "regulatory_body": "State Real Estate Division",
    "regulatory_url": "https://www.arello.org/",
    "notes": "Jurisdiction not in primary database. Verify all statute citations with local counsel.",
}


def get_state_statutes(state_code: str) -> dict:
    """Return statute data for a state, falling back to defaults for unlisted states."""
    return _STATE_STATUTES.get(state_code.upper() if state_code else "", _DEFAULT_STATUTE)


def get_federal_statutes() -> list[dict]:
    """Federal laws applicable to all timeshare cases."""
    return [
        {
            "name": "FTC Act — Section 5 (Unfair or Deceptive Acts or Practices)",
            "citation": "15 U.S.C. § 45",
            "provision": "Prohibits unfair or deceptive acts or practices in commerce",
            "how_applies": "High-pressure sales tactics and material misrepresentations constitute unfair or deceptive acts",
            "remedies": ["FTC enforcement action", "Civil penalty up to $50,120 per violation (2024)", "Restitution"],
        },
        {
            "name": "Truth in Lending Act (TILA)",
            "citation": "15 U.S.C. §§ 1601–1667f; Regulation Z, 12 C.F.R. Part 1026",
            "provision": "Requires clear disclosure of credit terms including APR, total cost of credit",
            "how_applies": "Timeshare financing often involves undisclosed or inadequately disclosed interest charges",
            "remedies": ["Right to rescind", "Actual damages", "Statutory damages up to $2,000", "Attorney fees"],
        },
        {
            "name": "Real Estate Settlement Procedures Act (RESPA)",
            "citation": "12 U.S.C. §§ 2601–2617; Regulation X, 12 C.F.R. Part 1024",
            "provision": "Requires disclosure of settlement costs; prohibits kickbacks and fee splitting",
            "how_applies": "Applies to timeshare purchase loans; undisclosed fees may constitute RESPA violations",
            "remedies": ["3x damages for kickback violations", "Actual damages", "Attorney fees"],
        },
    ]


def get_regulatory_bodies(state_code: str) -> list[dict]:
    """Return regulatory bodies relevant to a state's timeshare cases."""
    state_data = get_state_statutes(state_code)
    return [
        {
            "name": "Consumer Financial Protection Bureau (CFPB)",
            "complaint_url": "https://www.consumerfinance.gov/complaint/",
            "notes": "File as 'Mortgage' complaint. CFPB has jurisdiction over timeshare mortgage loans.",
        },
        {
            "name": f"{state_data.get('state', 'State')} Attorney General",
            "complaint_url": state_data.get("state_ag_complaint_url", "https://www.naag.org/find-my-ag/"),
            "notes": "State AG can investigate and bring enforcement actions for consumer protection violations.",
        },
        {
            "name": state_data.get("regulatory_body", "State Real Estate Division"),
            "complaint_url": state_data.get("regulatory_url", ""),
            "notes": "Licenses timeshare developers; can revoke licenses for statutory violations.",
        },
        {
            "name": "Federal Trade Commission (FTC)",
            "complaint_url": "https://reportfraud.ftc.gov/",
            "notes": "FTC has jurisdiction over interstate timeshare fraud under Section 5 of the FTC Act.",
        },
    ]
